name: Tests & checks

on:
  pull_request:
  workflow_dispatch: # allow running manually from the Actions tab

# cancel previous runs on a new commit
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          # fetch origin/master to be able to compare it to current branch
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      # make sure cache directory exists at this stage, otherwise cache
      # will always be ignored
      - name: Create dataset cache directory
        run: mkdir -p ~/scikit_learn_data

      - name: Cache datasets
        uses: actions/cache@v5
        with:
          # GitHub Actions can't create a cache key on dataset contents, so we use
          # dataset loader .py files instead
          path: ~/scikit_learn_data
          key: datasets-${{ runner.os }}-${{ hashFiles('skfp/datasets/**/*.py') }}

      - name: Install the project dependencies
        run: uv sync --group test

      - name: Check pre-commit
        run: uv run pre-commit run --all-files

      - name: Run tests with pytest
        run: uv run make test

      - name: Run docstring tests
        run: uv run make -C docs doctest
